---
title: "VGLM_Test"
output: html_document
date: "2025-03-24"
---

```{r}
library(VGAM)
data <- data.frame(
  Y_A = c(1, 1, 0, 1, 0, 1, 1, 0, 1, 0),
  Y_B = c(0, 1, 0, 1, 0, 1, 0, 0, 1, 1),
  Hours = c(5, 6, 3, 7, 2, 8, 4, 3, 6, 5),
  IQ = c(110, 120, 95, 115, 100, 130, 105, 90, 125, 108)
)
data$Y_combined <- factor(paste(data$Y_A, data$Y_B, sep = ","))
fit_yee <- vglm(Y_combined ~ Hours + IQ, family = multinomial(refLevel = "0,0"), data = data)
coef(fit_yee, matrix = TRUE)
summary(fit_yee)
```

```{r}
library(copula)
data <- data.frame(
  Y_A = c(1, 1, 0, 1, 0, 1, 1, 0, 1, 0),
  Y_B = c(0, 1, 0, 1, 0, 1, 0, 0, 1, 1),
  Hours = c(5, 6, 3, 7, 2, 8, 4, 3, 6, 5),
  IQ = c(110, 120, 95, 115, 100, 130, 105, 90, 125, 108)
)
# Mô hình logistic riêng cho Y_A và Y_B
fit_A <- glm(Y_A ~ Hours + IQ, family = binomial, data = data)
fit_B <- glm(Y_B ~ Hours + IQ, family = binomial, data = data)
# Ước lượng copula (giả định)
cop <- normalCopula(param = 0.6, dim = 2)  # Tương quan giả định 0.6
# Tính xác suất chung cần lập trình thêm likelihood với copula
```

